# -*- coding: utf-8 -*-
{
    'name': "AGP Employee",
    'summary': "Enhancements for Employee Management AGP, including detailed data, history, and specific workflows.",
    'description': """
        This module extends Odoo's HR capabilities for AGP, focusing on:
        - Detailed employee information (personal, job, salary, koperasi, uniform).
        - Comprehensive job history (histori_jabatan) with contract linking.
        - Custom leave approval workflows.
        - Management of company regulations, UMK, insurance, and TAD vendors.
        - Employee dashboard and custom reports.
    """,
    'author': "Abhimantra - Ibad",
    'website': "https://abhimantra.co.id/",
    'category': 'HR/Employee',
    'version': '16.0.1.3.8',
    'depends': [
        'web',
        'base',
        'mail',
        'base_setup',
        'contacts',
        'calendar',
        'base_multi_branch',
        'agp_custom_fields',
        'hr',
        'hr_employee_updation',
        'hr_org_chart',
        'hr_attendance',
        'hr_payroll_community',
        'hr_skills',
        'hr_contract',
        # 'hr_holidays',
        'hr_expense',
        'hr_recruitment',
        'hr_resignation',
        'hr_hourly_cost',
    ],
    'data': [
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/sequence.xml',
        'wizard/hr_employee_history_wizard_view.xml',
        'wizard/wizard_import_employee_view.xml',
        # 'wizard/hr_leave_reject_wizard_view.xml',
        # 'wizard/hr_leave_ask_for_revision_wizard_view.xml',
        'wizard/bulk_upload_attachment_view.xml',
        'views/res_users_view.xml',
        'views/hr_branch_view.xml',
        'views/odoo_payroll_grade_view.xml',
        'views/umk_master_view.xml',
        'views/agp_vendor_tad_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_department_view.xml',
        # 'views/hr_leave_view.xml',
        # 'views/hr_leave_type_views.xml',
        'views/hr_employee_unit_view.xml',
        'views/hr_employee_keterangan_jabatan_view.xml',
        'views/hr_employee_kelompok_umur_view.xml',
        'views/hr_employee_fungsi_penugasan_view.xml',
        'views/hr_employee_unit_penempatan_view.xml',
        'views/hr_employee_status_pajak_view.xml',
        'views/hr_employee_uniform_view.xml',
        'views/hr_employee_unit_penempatan_cabang_view.xml',
        # 'views/hr_leave_allocation_rule_view.xml',
        'views/hr_asuransi_view.xml',
        'views/hr_employee_menuitem.xml',
        # 'views/hr_leave_menuitem.xml',
        'report/employee_uniform_report_view.xml',
        'report/report_employee_template.xml',
        'report/report_employee.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'agp_employee_ib/static/src/lib/*.js',
            'agp_employee_ib/static/src/views/**/*.js',
            'agp_employee_ib/static/src/views/**/*.xml',
            'agp_employee_ib/static/src/js/employee_dashboard.js',
            'agp_employee_ib/static/src/css/dashboard_styles.css',
            'agp_employee_ib/static/src/css/style.css',
            'agp_employee_ib/static/src/xml/employee_dashboard.xml',
            'agp_employee_ib/static/src/xml/time_off_dashboard.xml',
        ]
    },
    'installable': True,
    'application': True,
    'icon': '/agp_employee_ib/static/description/icon.png',
    'license': 'LGPL-3',
}