{
    "name"          : "Laporan Accounting Multi Branch",
    "summary"       : "Laporan Accounting Multi Branch",
    "version"       : "1.0",
    "author"        : "AGP",
    "category"      : "Extra Tools",
    "license"       : "LGPL-3",
    "depends"       : [
        "account",
        "base_multi_branch",
        "accounting_pdf_reports",
        "agp_custom_fields",
        "web",
        "hr"
    ],
    "data"          : [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "report/neraca.xml",
        "report/laba_rugi_pusat.xml",
        "report/laba_rugi_cabang.xml",
        "report/aging_ap.xml",
        "report/aging_ap_detail.xml",
        "report/aging_ar.xml",
        "report/aging_ar_detail.xml",
        "report/aging_posisi_ar.xml",
        "report/hutang_piutang.xml",
        "report/neraca_summary.xml",
        "report/laba_rugi_summary.xml",
        "report/perubahan_equitas.xml",
        "report/cashflow.xml",
        "report/compare_tax.xml",
        "report/credit_note.xml",
        "report/debit_note.xml",
        "report/penerimaan_pelunasan_hutang.xml",
        "report/permintaan_pembayaran.xml",
        "report/kartu_neraca.xml",
        "report/penerimaan_kas_masuk.xml",
        "report/invoice_new.xml",
        "views/financial_data.xml",
        "views/financial_param.xml",
        # "views/account_move.xml",
        "views/account_move_inherit.xml",
        "views/dirjen_pajak.xml",
        "views/credit_note.xml",
        "views/debit_note.xml",
        "views/permintaan_pembayaran.xml",
        "wizard/neraca_wizard.xml",
        "wizard/neraca_summary_wizard.xml",
        "wizard/laba_rugi_wizard.xml",
        "wizard/laba_rugi_summary.xml",
        "wizard/perubahan_equitas.xml",
        "wizard/cashflow.xml",
        "wizard/aging_ap.xml",
        "wizard/aging_ap_detail.xml",
        "wizard/aging_ar.xml",
        "wizard/aging_ar_detail.xml",        
        "wizard/aging_posisi_ar.xml",
        "wizard/hutang_piutang.xml",
        "wizard/compare_tax.xml",        
        "wizard/kartu_neraca.xml",
        "wizard/rk.xml",
    ],

    "application"   : True,
    "installable"   : True,
    "auto_install"  : False,
}